version: "3"

services:
  wgcf:
    image: ghcr.io/hx210/wgcf-docker
    container_name: wgcf
    restart: unless-stopped
    ports:
      - "5001:1080"
    volumes:
      - $HOME/conf/wgcf:/wgcf
      - /lib/modules:/lib/modules
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    cap_add:
      - NET_ADMIN
