version: "3"

services:
  wgcf:
    image: ghcr.io/hx210/wgcf-docker
    container_name: wgcf
    restart: unless-stopped
    networks:
      - proxy_warp_net
    ports:
      - "5001:1080"
    volumes:
      - /etc/config/wgcf/conf:/wgcf
      - /lib/modules:/lib/modules:ro
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    cap_add:
      - NET_ADMIN

networks:
  proxy_warp_net:
