name: Test
on:
  workflow_dispatch:

  push:
    branches:
      - "*"
    paths:
      - "**"
      - "!**.md"

  pull_request:
    branches:
      - "*"
    paths:
      - "**"
      - "!**.md"

jobs:
  Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t wg-alpine . -f Dockerfile.alpine
      - name: Test single container
        run: |
          docker run -dit \
          --name wgcf \
          --sysctl net.ipv6.conf.all.disable_ipv6=0 \
          --privileged --cap-add net_admin \
          -v /lib/modules:/lib/modules \
          -v $(pwd)/wgcf:/wgcf \
          wg-alpine
          while ! docker logs wgcf | grep "is up"; do
            echo wait
            sleep 1
          done
          docker exec -i wgcf curl ipinfo.io
          docker exec -i wgcf curl ipv6.ip.sb

      - name: Test single container V4
        run: |
          docker run --rm   --network container:wgcf  curlimages/curl curl ipinfo.io

      - name: Test single container V6
        run: |
          docker run --rm   --network container:wgcf  curlimages/curl curl ipv6.ip.sb
          docker rm -f wgcf
